"""Add API Keys

Revision ID: 9d3521940db2
Revises: b6582892a9ab
Create Date: 2026-07-28 16:42:45.527198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3521940db2'
down_revision: Union[str, Sequence[str], None] = 'b6582892a9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('groq_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('tavily_api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tavily_api_key')
    op.drop_column('users', 'groq_api_key')
    # ### end Alembic commands ###
